import CATALOG_IMAGES from '@/data/catalogImages.json';

/**
 * Real catalog listings (imported supplier stock) carry no photo in the feed.
 * Staff photos live in products.image_url and always win; this is the
 * fallback: a studio render per model, generated by
 * tooling/image-gen/generate-catalog.mjs, which also writes catalogImages.json
 * (normalized model → asset id) for the renders that exist on disk.
 *
 * Exact match only. The old substring match picked the first family that
 * overlapped, so an iPhone 16 showed a 16 Pro Max render — a placeholder tile
 * is better than the wrong device. Returns null when nothing matches.
 */
const IMAGES: Record<string, string> = CATALOG_IMAGES;

/** Folds the supplier's spelling variants onto one key. Keep in sync with
 * tooling/image-gen/catalog-manifest.mjs normalizeModel(). */
export function normalizeModel(model: string): string {
  return model
    .toLowerCase()
    .replace(/\+/g, ' plus ')
    .replace(/\bfan edition\b/g, 'fe')
    .replace(/\b5g\b/g, '')
    .replace(/\b(fold|flip)\s+(\d)\b/g, '$1$2')
    .replace(/\s+/g, ' ')
    .trim();
}

export function resolveProductImage(model: string): string | null {
  const id = IMAGES[normalizeModel(model)];
  return id ? `/generated/catalog/${id}.webp` : null;
}
